services:
   nginx:
      image: nginx:alpine
      container_name: nginx
      ports:
        - "8080:80"
      volumes:
        # - ./site:/usr/share/nginx/html       # Serve blog at /
        # - ./site/nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./site/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
          - ./site:/usr/share/nginx/html:ro
      depends_on:
        - frontend
        - backend
   frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        working_dir: /frontend
        env_file:
          - ./frontend/.env.local
        ports:
            - "3000:3000"
        volumes:  # ✅ Matches your WORKDIR
            - /frontend/node_modules


        # docker-compose up -d

   backend:
        build:
          context: ./webadmin
          dockerfile: Dockerfile
        # docker-compose up -d
        ports:
          - "8000:8000"
        volumes:
          - ./webadmin:/webadmin  # ✅ Matches your WORKDIR

        env_file:
          - .env

        depends_on:
          - db
        command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000

   db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
   