# Generated by Django 4.2.23 on 2025-07-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, help_text='ImgBB image URL', max_length=500, null=True),
        ),
    ]
