# Generated by Django 4.2.23 on 2025-07-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
