# Generated by Django 4.2.23 on 2025-07-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, help_text='URL for the article detail page', max_length=500, null=True),
        ),
    ]
