# Generated by Django 4.2.23 on 2025-07-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Your Site Title', help_text='Main site title displayed in header', max_length=200)),
                ('site_subtitle', models.CharField(blank=True, help_text='Subtitle or tagline displayed in header', max_length=300, null=True)),
                ('header_logo_url', models.URLField(blank=True, help_text='URL for header logo image', max_length=500, null=True)),
                ('header_background_color', models.CharField(default='#ffffff', help_text='Header background color (hex code)', max_length=7)),
                ('header_text_color', models.CharField(default='#000000', help_text='Header text color (hex code)', max_length=7)),
                ('show_header', models.BooleanField(default=True, help_text='Whether to show the header on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Header Setting',
                'verbose_name_plural': 'Header Settings',
            },
        ),
    ]
